[variables]
NODE_ENV = "production"
SECRET_KEY = "Mestre888"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[phases.setup]
nixPkgs = ["nodejs_18", "chromium"]

[phases.install]
cmds = ["npm install --production --legacy-peer-deps --ignore-optional"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/server.js"
